-- Aircraft history for Boeing aircraft (excluding 747-400, 787-9, 737-800 which already have history)
-- Researched: 2026-01-20

-- Boeing 737 MAX 8 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-737-max-8', 'development', 2011, 'Program Launch', 'The 737 MAX project was officially launched in 2011, with Boeing announcing that the aircraft would feature new CFM LEAP-1B engines, improved aerodynamics with split-tip winglets, and advanced avionics to compete with the Airbus A320neo family.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-8', 'milestone', 2016, 'First Flight', 'The first 737 MAX 8 took to the skies on January 29, 2016, from Renton Field in Washington state, beginning an extensive flight test program.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-8', 'milestone', 2017, 'FAA Certification and First Delivery', 'The FAA certified the 737 MAX for flight in March 2017. The first delivery went to Malindo Air (owned by Lion Air of Indonesia) in May 2017, marking entry into commercial service.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-8', 'incident', 2018, 'Lion Air Flight 610', 'On October 29, 2018, Lion Air Flight 610 crashed into the Java Sea shortly after takeoff from Jakarta, killing all 189 people on board. Investigations revealed issues with the MCAS flight control system.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX_groundings', 'Wikipedia'),
('boeing-737-max-8', 'incident', 2019, 'Ethiopian Airlines Flight 302 and Global Grounding', 'On March 10, 2019, Ethiopian Airlines Flight 302 crashed, killing 157 people. Within days, aviation authorities worldwide grounded all 387 Boeing 737 MAX aircraft - the first global fleet grounding since 1979.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX_groundings', 'Wikipedia'),
('boeing-737-max-8', 'milestone', 2020, 'Return to Service', 'After 20 months of grounding, software fixes, and revised pilot training, the FAA cleared the 737 MAX to return to service in November 2020. By late 2021, most countries had lifted their grounding orders.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-8', 'incident', 2024, 'Door Plug Incident', 'On January 5, 2024, a door plug panel blew off an Alaska Airlines 737 MAX 9 mid-flight. Investigation revealed four bolts were missing after factory repair work, leading to renewed FAA scrutiny of Boeing manufacturing.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-8', 'legacy', NULL, 'Most Ordered Commercial Aircraft', 'Despite its troubled history, the 737 MAX remains one of the most ordered aircraft families ever, with thousands of orders from airlines worldwide seeking its 20% fuel efficiency improvement over the previous 737NG.', 'https://www.boeing.com/commercial/737max', 'Boeing');

-- Boeing 737 MAX 9 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-737-max-9', 'development', 2017, 'First Flight', 'The stretched 737 MAX 9 completed its first flight on April 13, 2017, designed to offer more capacity than the MAX 8 while targeting the market previously served by the 737-900ER.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-9', 'milestone', 2018, 'Entry into Service', 'The MAX 9 entered commercial service with Lion Air in March 2018, offering airlines up to 220 passengers in a high-density configuration.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-9', 'fact', NULL, 'Mid-Cabin Exit Door', 'The MAX 9 features a rear mid-cabin exit door on each side that is required for high-density seating configurations above 189 passengers, giving airlines flexibility in cabin layouts.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-9', 'story', NULL, 'United and Alaska Favorite', 'United Airlines and Alaska Airlines have become the largest operators of the 737 MAX 9, using it to modernize their domestic fleets with improved fuel efficiency on medium-capacity routes.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia');

-- Boeing 737 MAX 10 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-737-max-10', 'development', 2017, 'Program Announcement', 'Boeing officially launched the 737 MAX 10 at the 2017 Paris Air Show with over 240 orders and commitments, positioning it as a direct competitor to the Airbus A321neo.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-10', 'milestone', 2021, 'First Flight', 'The 737 MAX 10 completed its first flight on June 18, 2021, from Renton Field. At 43.8 meters long, it became the longest 737 variant ever built.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-10', 'fact', NULL, 'Innovative Landing Gear', 'The MAX 10 uses taller, levered landing gear that retracts into a shortened wheel well, allowing the longer fuselage to maintain adequate ground clearance during rotation without major structural changes.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-10', 'story', NULL, 'Filling the 757 Gap', 'The MAX 10 was specifically designed to help airlines replace their aging Boeing 757s on high-density domestic routes, offering similar passenger capacity with better economics.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia');

-- Boeing 737 MAX 7 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-737-max-7', 'development', 2018, 'First Flight', 'The 737 MAX 7 completed its maiden flight on March 16, 2018, the smallest member of the MAX family designed to replace the popular 737-700.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-7', 'fact', NULL, 'Shared Components', 'The MAX 7 shares the same wing and landing gear as the larger MAX 8, simplifying production and pilot training while offering excellent hot-and-high airport performance.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia'),
('boeing-737-max-7', 'story', NULL, 'Southwest Airlines Future', 'Southwest Airlines, which built its entire fleet around the 737-700, is a major customer for the MAX 7 as it continues its single-aircraft-type strategy.', 'https://en.wikipedia.org/wiki/Boeing_737_MAX', 'Wikipedia');

-- Boeing 737-700 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-737-700', 'development', 1993, 'Program Launch', 'The 737-700 was launched in November 1993 as the base model of the 737 Next Generation family, designed to replace the aging 737-300 with modern avionics and improved efficiency.', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation', 'Wikipedia'),
('boeing-737-700', 'milestone', 1997, 'First Flight and Certification', 'The 737-700 first flew on February 9, 1997, and received FAA certification later that year, enabling deliveries to launch customer Southwest Airlines.', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation', 'Wikipedia'),
('boeing-737-700', 'story', NULL, 'Southwest Airlines Partnership', 'Southwest Airlines bet big on the 737-700, ordering hundreds of aircraft and becoming the largest operator. The airline valued its reliability and economics for point-to-point operations.', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation', 'Wikipedia'),
('boeing-737-700', 'fact', NULL, 'Business Jet Variant', 'Boeing developed the BBJ (Boeing Business Jet) based on the 737-700 airframe combined with the stronger wings and landing gear of the 737-800, popular with corporations and governments worldwide.', 'https://en.wikipedia.org/wiki/Boeing_Business_Jet', 'Wikipedia');

-- Boeing 737-900ER History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-737-900er', 'development', 2005, 'Program Launch', 'The 737-900ER was launched in 2005 as an extended-range version of the 737-900, featuring additional fuel tanks and two extra emergency exits to allow higher passenger capacity.', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation', 'Wikipedia'),
('boeing-737-900er', 'milestone', 2007, 'First Delivery', 'Lion Air received the first 737-900ER in April 2007, becoming the launch customer for Boeings longest Next Generation 737 variant.', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation', 'Wikipedia'),
('boeing-737-900er', 'fact', NULL, 'Split Scimitar Winglets', 'Many 737-900ERs have been retrofitted with Split Scimitar Winglets, which improve fuel efficiency by up to 2% and have become a distinctive visual feature of the type.', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation', 'Wikipedia'),
('boeing-737-900er', 'story', NULL, 'Alaska Airlines Workhorse', 'Alaska Airlines operates one of the largest 737-900ER fleets, using it extensively on West Coast routes where its range and capacity perfectly match demand.', 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation', 'Wikipedia');

-- Boeing 757-200 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-757-200', 'development', 1978, 'Clean Sheet Design', 'Boeing began developing the 757 as a clean-sheet replacement for the 727, initially designated 7N7. The decision to use two wing-mounted engines instead of three tail-mounted engines was revolutionary.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-200', 'milestone', 1982, 'First Flight', 'The prototype Boeing 757 made its first flight on February 19, 1982, from Renton Field, marking a new era in narrow-body aircraft design with its advanced two-crew glass cockpit.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-200', 'milestone', 1983, 'Entry into Service', 'Eastern Air Lines introduced the 757-200 on its first commercial flight from Atlanta to Tampa in January 1983, demonstrating 45% better fuel efficiency than the 727 it replaced.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-200', 'record', 1991, 'Tibetan High-Altitude Flight', 'On March 29, 1991, a 757 demonstrated its exceptional performance by taking off, circling, and landing at Tibets Gonggar Airport at 11,621 feet elevation on just one engine.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-200', 'fact', NULL, 'Ferrari of the Skies', 'The 757 earned nicknames including the Flying Pencil and Ferrari of the Skies due to its narrow fuselage and powerful engines that made it feel overpowered to many pilots.', 'https://simpleflying.com/boeing-757-brief-history/', 'Simple Flying'),
('boeing-757-200', 'story', NULL, 'ETOPS Pioneer', 'The 757 helped prove that twin-engine aircraft could safely operate long overwater routes, paving the way for ETOPS regulations that transformed transoceanic aviation.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-200', 'fact', NULL, 'Government Service', 'The US government operates several 757s as C-32 aircraft for transporting the Vice President, First Lady, and Secretary of State with extensive security and communications equipment.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-200', 'legacy', NULL, 'Irreplaceable Capability', 'Even decades after production ended in 2004, the 757s unique combination of capacity, range, and hot-and-high performance remains unmatched, forcing airlines to choose between smaller or larger replacements.', 'https://simpleflying.com/boeing-757-brief-history/', 'Simple Flying');

-- Boeing 757-300 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-757-300', 'development', 1996, 'Program Launch', 'Boeing announced the stretched 757-300 at the 1996 Farnborough Airshow with Condor as launch customer, adding 23.4 feet to create the longest single-aisle twinjet ever built.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-300', 'milestone', 1998, 'First Flight', 'The 757-300 completed its maiden flight on August 2, 1998, demonstrating the feasibility of stretching the already long 757 fuselage.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-300', 'fact', NULL, 'Tailskid Protection', 'Due to its exceptional length of 54.5 meters, the 757-300 features a retractable tailskid to prevent damage during rotation on takeoff when the tail gets very close to the runway.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia'),
('boeing-757-300', 'story', NULL, 'Charter Carrier Favorite', 'The 757-300 found its niche with charter and leisure carriers who valued its 20% extra capacity over the 757-200 for high-density holiday routes to sunny destinations.', 'https://en.wikipedia.org/wiki/Boeing_757', 'Wikipedia');

-- Boeing 767-300ER History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-767-300er', 'development', 1986, 'Program Launch', 'The 767-300ER was developed as an extended-range version of the stretched 767-300, featuring additional fuel capacity and higher takeoff weights for transatlantic operations.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-300er', 'milestone', 1988, 'Entry into Service', 'American Airlines became the first operator of the 767-300ER in 1988, using it to expand transatlantic service with better economics than larger widebodies.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-300er', 'record', 1989, 'ETOPS-180 Approval', 'The 767-300ER with GE CF6 engines became one of the first aircraft to receive ETOPS-180 approval in 1989, allowing it to fly up to 180 minutes from the nearest airfield.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-300er', 'fact', NULL, 'Best-Selling 767', 'The 767-300ER became the best-selling variant of the 767 family with over 580 delivered, proving the market demand for efficient medium-sized widebodies.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-300er', 'story', NULL, 'Comfortable 2-3-2 Layout', 'The 767s 2-3-2 economy configuration meant no passenger was ever more than one seat from the aisle, making it more comfortable than competing aircraft with middle seats in every row.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-300er', 'legacy', NULL, 'Freighter Conversion', 'Many retired 767-300ERs have found new life as converted freighters, with companies like Amazon and FedEx building large fleets of 767 cargo aircraft.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia');

-- Boeing 767-400ER History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-767-400er', 'development', 1997, 'Program Launch', 'Boeing launched the 767-400ER in 1997 as a stretched, long-range variant to compete with the Airbus A330, featuring a 21-foot fuselage stretch and new raked wingtips.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-400er', 'milestone', 1999, 'First Flight', 'The 767-400ER made its first flight on October 9, 1999, showcasing its distinctive raked wingtips that would later appear on the 787 Dreamliner.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-400er', 'milestone', 2000, 'Entry into Service', 'Continental Airlines (now United) put the 767-400ER into service in September 2000, using it for both domestic transcontinental and international routes.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-400er', 'fact', NULL, 'Raked Wingtip Pioneer', 'The 767-400ER was the first commercial aircraft to use raked wingtips, a technology that improves aerodynamic efficiency and later became standard on the 787 and 777X.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia'),
('boeing-767-400er', 'story', NULL, 'Limited Production', 'Only 38 767-400ERs were built for just two customers (Continental and Delta), making it the rarest 767 variant and a favorite among aviation enthusiasts.', 'https://en.wikipedia.org/wiki/Boeing_767', 'Wikipedia');

-- Boeing 777-200ER History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-777-200er', 'development', 1996, 'Program Launch', 'The 777-200ER was developed to extend the range of the original 777-200, featuring higher maximum takeoff weight and additional fuel capacity for true long-haul capability.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200er', 'milestone', 1997, 'Entry into Service', 'British Airways became the first operator of the 777-200ER in February 1997, using it on transatlantic routes where its ETOPS capability enabled efficient twin-engine operations.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200er', 'fact', NULL, 'Most Popular 777', 'The 777-200ER became the most widely sold variant of the original 777 family with over 420 delivered, forming the backbone of international operations for airlines worldwide.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200er', 'story', NULL, 'Engine Choices', 'Airlines could choose from three engine options: GE90, Pratt & Whitney PW4000, or Rolls-Royce Trent 800, giving unprecedented flexibility in powerplant selection.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200er', 'legacy', NULL, 'Proven Reliability', 'The 777-200ER established the 777s reputation for exceptional reliability and performance, with aircraft logging tens of thousands of hours in service over two decades.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia');

-- Boeing 777-200LR History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-777-200lr', 'development', 2002, 'Ultra-Long-Range Design', 'Boeing developed the 777-200LR Worldliner to fly farther than any other commercial aircraft, using three additional fuel tanks and the powerful GE90-110B1L engines.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200lr', 'milestone', 2005, 'First Flight', 'The 777-200LR completed its maiden flight on March 8, 2005, from Everett, Washington, beginning a flight test program to validate its extraordinary range capabilities.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200lr', 'record', 2005, 'Longest Commercial Flight Record', 'In November 2005, a 777-200LR set the world record for longest non-stop flight by a commercial aircraft, traveling 21,602 km from Hong Kong to London flying eastward over the Pacific in 22 hours 42 minutes.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200lr', 'fact', NULL, 'Worldliner Nickname', 'The 777-200LR earned the Worldliner nickname because its 17,445 km range allows it to connect virtually any two cities on Earth non-stop.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-200lr', 'story', NULL, 'Opening New Routes', 'Airlines used the 777-200LR to open previously impossible routes like Dallas-Sydney and Newark-Hong Kong, connecting markets that couldnt be served non-stop before.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia');

-- Boeing 777-300ER History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-777-300er', 'development', 2002, 'Program Launch', 'Boeing launched the 777-300ER to combine the stretched fuselage of the 777-300 with the extended range capabilities and GE90-115B engines developed for the 777-200LR.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-300er', 'milestone', 2003, 'First Flight', 'The 777-300ER completed its first flight on February 24, 2003, showcasing its ability to carry more passengers farther than any previous 777 variant.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-300er', 'milestone', 2004, 'Entry into Service', 'Air France became the first operator of the 777-300ER in April 2004, beginning a remarkably successful commercial career.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-300er', 'fact', NULL, 'Worlds Most Powerful Engine', 'The GE90-115B engines on the 777-300ER produce 115,300 pounds of thrust each, making them the most powerful jet engines ever to enter service.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-300er', 'record', NULL, 'Best-Selling Widebody', 'The 777-300ER became one of the best-selling widebody aircraft of all time with over 800 delivered, replacing the Boeing 747 as the long-haul aircraft of choice.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-300er', 'story', NULL, 'Emirates Flagship', 'Emirates built the worlds largest 777 fleet, using the -300ER as its flagship aircraft connecting Dubai to destinations across six continents.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia'),
('boeing-777-300er', 'legacy', NULL, 'Defining a Generation', 'The 777-300ER defined long-haul twin-engine travel for nearly two decades, proving that twins could match the range and capacity of four-engine jumbos with better economics.', 'https://en.wikipedia.org/wiki/Boeing_777', 'Wikipedia');

-- Boeing 777-9 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-777-9', 'development', 2013, 'Program Launch', 'Boeing formally launched the 777X program in November 2013 with 259 orders from Emirates, Lufthansa, Qatar Airways, and Etihad Airways, introducing revolutionary folding wingtips.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-9', 'milestone', 2019, 'Rollout', 'The first 777-9 prototype was rolled out on March 13, 2019, revealing its massive 72-meter wingspan with the distinctive folding wingtips in their deployed position.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-9', 'milestone', 2020, 'First Flight', 'The 777-9 completed its first flight on January 25, 2020, a 3-hour 52-minute flight from Paine Field to Boeing Field that marked a new chapter in widebody development.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-9', 'fact', NULL, 'Folding Wingtips', 'The 777-9s wingtips fold upward to reduce wingspan from 72m to 65m, allowing it to use the same airport gates as the current 777 despite having much larger wings.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-9', 'fact', NULL, 'GE9X Engines', 'The 777-9 is powered by the GE9X, the worlds largest and most powerful commercial aircraft engine, with a fan diameter of 3.4 meters (11 feet).', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-9', 'story', NULL, 'Composite Wings', 'Boeing built a $1 billion Composite Wing Center to manufacture the 777Xs massive carbon-fiber wings in-house, the largest Boeing has ever produced.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-9', 'incident', 2024, 'Certification Delays', 'The 777-9 faced multiple certification delays, with entry into service pushed to 2027 as Boeing worked through regulatory requirements following heightened FAA scrutiny.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia');

-- Boeing 777-8 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-777-8', 'development', 2013, 'Program Launch', 'The 777-8 was launched alongside the 777-9 as the ultra-long-range variant of the 777X family, designed to replace the 777-200LR with even greater range and efficiency.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-8', 'milestone', 2024, 'First Flight', 'After years of focusing on the 777-9, Boeing completed the first flight of the 777-8 in 2024, demonstrating the ultra-long-range variants capabilities.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-8', 'fact', NULL, 'Ultimate Range', 'The 777-8 can fly farther than any other twin-engine commercial aircraft at 16,170 km, capable of connecting virtually any two cities on Earth non-stop.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia'),
('boeing-777-8', 'story', NULL, 'Emirates Order', 'Emirates has ordered 35 Boeing 777-8s, planning to use them on routes requiring maximum range including potential new ultra-long-haul connections.', 'https://en.wikipedia.org/wiki/Boeing_777X', 'Wikipedia');

-- Boeing 787-8 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-787-8', 'development', 2004, 'Program Launch', 'Boeing launched the 787 Dreamliner program in April 2004, promising revolutionary composite construction and 20% better fuel efficiency than existing aircraft.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-8', 'milestone', 2009, 'First Flight', 'After numerous delays, the first 787-8 took flight on December 15, 2009, from Paine Field, marking a historic moment for composite commercial aircraft construction.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-8', 'milestone', 2011, 'First Delivery', 'All Nippon Airways received the first 787-8 on September 25, 2011, more than three years behind original schedule but beginning a new era in aviation.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-8', 'incident', 2013, 'Battery Grounding', 'In January 2013, the global 787 fleet was grounded for three months due to lithium-ion battery fires, the first grounding of an entire aircraft type since 1979.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-8', 'fact', NULL, 'Composite Construction', 'The 787-8 was the first commercial airliner with a fuselage made primarily of carbon-fiber composites, making up 50% of the airframe by weight.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-8', 'story', NULL, 'Passenger Comfort Revolution', 'The 787 introduced numerous passenger comfort features including larger windows, higher cabin pressure, better humidity, and advanced air filtration systems.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia');

-- Boeing 787-10 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-787-10', 'development', 2013, 'Program Launch', 'Boeing launched the 787-10 at the 2013 Paris Air Show as the largest Dreamliner variant, stretched 5.5 meters longer than the 787-9 for high-density routes.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-10', 'milestone', 2017, 'First Flight', 'The 787-10 completed its first flight on March 31, 2017, from North Charleston, South Carolina, where it is exclusively assembled.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-10', 'milestone', 2018, 'Entry into Service', 'Singapore Airlines put the first 787-10 into service in April 2018, using it on regional routes within Asia where its capacity matched demand.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-10', 'fact', NULL, '90% Route Coverage', 'Despite having shorter range than its siblings, the 787-10 can cover over 90% of the worlds twin-aisle routes, as most routes dont require ultra-long range.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia'),
('boeing-787-10', 'story', NULL, 'United Airlines Fleet', 'United Airlines has become a major 787-10 operator, using the largest Dreamliner for transcontinental and medium-haul international routes from its US hubs.', 'https://en.wikipedia.org/wiki/Boeing_787_Dreamliner', 'Wikipedia');

-- Boeing 747-8 Intercontinental History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('boeing-747-8i', 'development', 2005, 'Program Launch', 'Boeing launched the 747-8 program in November 2005 as an advanced development incorporating 787 technology into the iconic 747 platform.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia'),
('boeing-747-8i', 'milestone', 2011, 'First Passenger Flight', 'The 747-8 Intercontinental passenger variant completed its first flight on March 20, 2011, showcasing its stretched fuselage and new raked wingtips.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia'),
('boeing-747-8i', 'milestone', 2012, 'Entry into Service', 'Lufthansa inaugurated 747-8I service in June 2012, becoming the European launch customer for the worlds longest airliner at the time.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia'),
('boeing-747-8i', 'fact', NULL, 'Worlds Longest Airliner', 'At 76.3 meters, the 747-8 became the worlds longest airliner ever built, surpassing the Airbus A340-600 that previously held the record.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia'),
('boeing-747-8i', 'fact', NULL, '787 Technology', 'The 747-8 incorporated technology from the 787 Dreamliner including the GEnx engines, raked wingtips, and advanced aerodynamics for improved efficiency.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia'),
('boeing-747-8i', 'story', NULL, 'Air Force One', 'Two 747-8s are being modified as the next generation Air Force One (VC-25B), continuing the tradition of the 747 serving as the US presidential aircraft.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia'),
('boeing-747-8i', 'milestone', 2023, 'End of an Era', 'The final Boeing 747 rolled off the assembly line on January 31, 2023, ending 54 years of production. It was the last commercial four-engine passenger aircraft in production.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia'),
('boeing-747-8i', 'legacy', NULL, 'Jumbo Jet Legacy', 'The 747-8 represented the final evolution of the jumbo jet era, proving there was still a place for four-engine giants even as efficient twins dominated the market.', 'https://en.wikipedia.org/wiki/Boeing_747-8', 'Wikipedia');
