-- Aircraft history for Embraer and Bombardier regional aircraft
-- Researched: 2026-01-20

-- Embraer E175 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('embraer-e175', 'development', 1999, 'E-Jet Program Launch', 'Embraer launched the E-Jet program at the 1999 Paris Air Show, aiming to bridge the gap between small regional jets and larger mainline aircraft.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia'),
('embraer-e175', 'milestone', 2003, 'First Flight', 'The E175 (officially E-170-200) completed its maiden flight on June 14, 2003, from Sao Jose dos Campos, Brazil.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia'),
('embraer-e175', 'milestone', 2005, 'Entry into Service', 'Air Canada became the first E175 operator in May 2005, introducing the stretched variant to North American regional operations.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia'),
('embraer-e175', 'fact', NULL, 'Scope Clause Champion', 'The E175 became immensely popular with US regional airlines because its weight falls just under pilot union scope clause limits, allowing it to be operated by regional affiliates.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia'),
('embraer-e175', 'fact', NULL, 'Double-Bubble Fuselage', 'The E-Jet family features a double-bubble fuselage cross-section with a 2-2 seating configuration, meaning no middle seats - a passenger favorite.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia'),
('embraer-e175', 'story', NULL, 'US Regional Workhorse', 'The E175 dominates US regional aviation, with over 500 in service at carriers like SkyWest, Republic Airways, and Envoy Air feeding passengers to major hubs.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia'),
('embraer-e175', 'story', NULL, 'E175-E2 Challenges', 'The next-generation E175-E2 has been repeatedly delayed because its higher weight exceeds scope clause limits, ironically making the older E175 more desirable to US carriers.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e175', 'record', 2025, '1900th E-Jet Delivered', 'Embraer delivered the 1,900th E-Jet family aircraft in September 2025, demonstrating the programs remarkable commercial success.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia'),
('embraer-e175', 'legacy', NULL, 'Redefining Regional Aviation', 'The E175 transformed regional aviation by offering a true jet experience with comfort rivaling mainline aircraft, helping airlines provide quality service on thinner routes.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_family', 'Wikipedia');

-- Embraer E190-E2 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('embraer-e190-e2', 'development', 2011, 'E2 Program Announcement', 'Embraer announced the E-Jet E2 family in November 2011, featuring new Pratt & Whitney geared turbofan engines and redesigned wings for dramatically improved efficiency.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'milestone', 2013, 'Program Launch', 'The E-Jet E2 program was formally launched at the 2013 Paris Air Show, with the E190-E2 as the first variant to be developed.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'milestone', 2016, 'First Flight', 'The E190-E2 completed its maiden flight on May 23, 2016, from Sao Jose dos Campos, demonstrating the new wings and engines.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'milestone', 2018, 'Entry into Service', 'Norwegian regional carrier Wideroe became the first E190-E2 operator on April 24, 2018, using it on challenging Norwegian routes.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'fact', NULL, 'Profit Hunter', 'Embraer markets the E2 family as Profit Hunter, emphasizing their fuel efficiency - up to 25% better than first-generation E-Jets.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'fact', NULL, 'Highest Aspect Ratio Wing', 'The E2 features the highest aspect ratio wing of any commercial airliner at just over 11, optimized for aerodynamic efficiency.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'fact', NULL, 'Geared Turbofan Technology', 'The Pratt & Whitney PW1900G geared turbofan engines use a gear system to optimize fan and turbine speeds independently, dramatically improving efficiency.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'story', NULL, 'Fly-By-Wire Evolution', 'The E2 introduced fly-by-wire controls to the E-Jet family, bringing the advanced technology previously seen only on larger aircraft.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'story', NULL, 'Swiss Air Force Evaluation', 'Switzerland evaluated the E190-E2 as a candidate for its air policing mission, demonstrating the types versatility beyond passenger operations.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia'),
('embraer-e190-e2', 'legacy', NULL, 'Setting New Standards', 'The E190-E2 sets new standards for efficiency in the 100-seat market, forcing competitors to develop new designs to match its economics.', 'https://en.wikipedia.org/wiki/Embraer_E-Jet_E2_family', 'Wikipedia');

-- Bombardier CRJ-900 History
INSERT INTO aircraft_history (aircraft_slug, content_type, year, title, content, source_url, source_name) VALUES
('bombardier-crj-900', 'development', 1999, 'Program Launch', 'Bombardier launched the CRJ-900 as a stretched version of the CRJ-700 to offer larger regional jet capacity while maintaining the families commonality advantages.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'milestone', 2001, 'First Flight', 'The CRJ-900 completed its maiden flight on February 21, 2001, from Montreal Mirabel, demonstrating the stretched fuselage design.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'milestone', 2003, 'Entry into Service', 'Mesa Air Group became the first CRJ-900 operator in 2003, using it under contract for US Airways Express regional operations.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'fact', NULL, 'CRJ Family Evolution', 'The CRJ-900 traces its lineage to the Canadair Challenger business jet, which was stretched into the CRJ-100/200 and then into the CRJ-700/900/1000 series.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'fact', NULL, 'Common Type Rating', 'Pilots with a CRJ-200 type rating need only minimal differences training to fly the CRJ-900, reducing airline training costs significantly.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'story', NULL, 'SkyWest Fleet', 'SkyWest Airlines operates one of the worlds largest CRJ-900 fleets, using it to provide regional service for United, Delta, and American Airlines.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'story', NULL, 'Program Sale to Mitsubishi', 'Bombardier sold the CRJ program to Mitsubishi in 2020, though Mitsubishi later shut down regional aircraft manufacturing, leaving the CRJ with no new production.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'fact', NULL, '2-2 Seating Comfort', 'The CRJ-900s 2-2 seating configuration means every passenger has either a window or aisle seat, eliminating the unpopular middle seat.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia'),
('bombardier-crj-900', 'legacy', NULL, 'Regional Jet Pioneer', 'The CRJ family helped establish the regional jet concept, proving that jet service could be economically viable on routes previously served only by turboprops.', 'https://en.wikipedia.org/wiki/Bombardier_CRJ700_series', 'Wikipedia');
